version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ocr_postgres
    network_mode: host
    environment:
      POSTGRES_DB: ocr_docs
      POSTGRES_USER: ocr_user
      POSTGRES_PASSWORD: ocr_secure_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ocr_backend
    network_mode: host
    environment:
      - DATABASE_URL=postgresql://ocr_user:ocr_secure_2024@localhost:5432/ocr_docs
      - PYTHONPATH=/app
      - PORT=8081
      - TESSERACT_CMD=/usr/bin/tesseract
    volumes:
      - backend_data:/app/pdfs
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ocr_frontend
    network_mode: host
    environment:
      - VITE_API_BASE_URL=http://localhost:8081/api
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_data: